### ISSUE TITLE
Annoying background music

### ISSUE THREAD

**Issue by timstott** [timstott/lotus-rouge#5]

**Comment by timstott** [comment]
[This is](http://www.opuzz.com/displayproducts.asp?id=298&cat=World%A0-%A0Chinese&st=styles&pn=World%A0Music) the site!

**Comment by patrickjandrews** [comment]
http://www.opuzz.com/displayproduct2.asp?id=2262&pn=World%A0Music&cat=World%A0-%A0Chinese

Second one for me

On 27 August 2014 15:24, Timothy Stott notifications@github.com wrote:

> This is
> http://www.opuzz.com/displayproducts.asp?id=298&cat=World%A0-%A0Chinese&st=styles&pn=World%A0Music
> the site!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/timstott/lotus-rouge/issues/5#issuecomment-53579653.

## 

_Patrick Andrews,_
Product Manager

_Enternships_
T: +44 (0) 203 397 3216
6 Briset St London EC1M 5NR

Confidentiality: This email and the contents are the property of
Enternships Ltd. If you are not the intended recipient of this message and
any attached files, please delete it. Unauthorised copying or distribution
of this message, its attachments or parts thereof, is strictly prohibited
unless specifically stated otherwise.

Please consider the environment before printing this message.

**Comment by timstott** [comment]
You read my mind! I’m already on it.

**Comment by patrickjandrews** [comment]
It's expensive no?

On 27 August 2014 15:29, Timothy Stott notifications@github.com wrote:

> You read my mind! I’m already on it.
> 
> On 27 Aug 2014, at 20:28, Patrick Andrews notifications@github.com
> wrote:
> 
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/timstott/lotus-rouge/issues/5#issuecomment-53580473.

## 

_Patrick Andrews,_
Product Manager

_Enternships_
T: +44 (0) 203 397 3216
6 Briset St London EC1M 5NR

Confidentiality: This email and the contents are the property of
Enternships Ltd. If you are not the intended recipient of this message and
any attached files, please delete it. Unauthorised copying or distribution
of this message, its attachments or parts thereof, is strictly prohibited
unless specifically stated otherwise.

Please consider the environment before printing this message.

**Comment by timstott** [comment]
They are all free :smile:
